#ifndef FRAMEBUFFER_CONSTANTS_H
#define FRAMEBUFFER_CONSTANTS_H

#define FRAMEBUFFER_HEIGHT_TILES 21
#define FRAMEBUFFER_WIDTH_TILES 32

#define FRAMEBUFFER_HEIGHT (FRAMEBUFFER_HEIGHT_TILES * 2)
#define FRAMEBUFFER_WIDTH (FRAMEBUFFER_WIDTH_TILES * 2)

#endif // not FRAMEBUFFER_CONSTANTS_H